import warnings
warnings.filterwarnings('ignore')
from ultralytics import YOLO


if __name__ == '__main__':
    model = YOLO(r'ultralytics\cfg\models\v8\yolov8n.yaml').load(r"yolov8n.pt")
    model.train(
        data=r'E:\Experiment\Yolo\.Trash-1000\files\ultralytics-yolo11-main\ultralytics\datasets\cub.yaml',
        epochs=300,
        patience=100,
        batch=32,
        imgsz=640,
        save=True,
        save_period=-1,
        cache=False,
        device='',
        workers=8,
        project='runs/train/cub',
        name='8n',
        exist_ok=False,
        pretrained=True,
        optimizer='Adam',
        verbose=True,
        seed=0,
        deterministic=True,
        single_cls=False,
        rect=False,
        cos_lr=False,
        close_mosaic=0,
        resume=False,
        amp=False,
        fraction=1.0,
        profile=False,
        freeze=None,
        lr0=0.001,
        lrf=0.001,
        momentum=0.937,
        weight_decay=0.0005,
        warmup_epochs=3.0,
        warmup_momentum=0.8,
        warmup_bias_lr=0.1,
        box=7.5,
        cls=0.5,
        dfl=1.5,
        pose=12.0,
        kobj=1.0,
        label_smoothing=0.0,
        nbs=64,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=0.0,
        translate=0.1,
        scale=0.5,
        shear=0.0,
        perspective=0.0,
        flipud=0.0,
        fliplr=0.5,
        mosaic=1.0,
        mixup=0.0,
        copy_paste=0.0,
    )
